add Hello for Greg
DHI-Roma/gregorovius-frontend pull request #26
Opened 2021-06-30 17:15 UTC by jhoernsc

## Issue

We want to say Hello to Greg

## What changed?

...

## How to test?

...

## Helpful Information

...

2021-06-30 17:16 UTC, suchmaske requested changes

2021-06-30 17:16 UTC, suchmaske commented on README.md
> +Hallo Gregor
His name is Greg, not Gregor

2021-06-30 17:17 UTC, suchmaske approved these changes
I was wrong!

2021-07-01 08:52 UTC, closed without merging

2021-07-08 09:42 UTC, jhoernsc commented
Lieber Herr Pohl,

leider muss ich ihnen für heute Abend krankheitsbedingt absagen. Könnten wir den Termin auf nach meinem Urlaub verschieben? In der Woche ab dem 20. wäre ich wieder zurück.
Tut mir wirklich leid, ich hoffe, das wirft ihre Pläne nicht zu sehr durcheinander.

Herzliche Grüße,
Jörg Hörnschemeyer

---------------------------------------------
Deutsches Historisches Institut
Istituto Storico Germanico
Via Aurelia Antica, 391
I-00165 Roma
Tel.: 0039-06-66049277
Fax: 0039-06-6623838
Email: ***@***.***

> From: Oliver Pohl ***@***.***>
> To: DHI-Roma/gregorovius-frontend ***@***.***>
> Cc: jhoernsc ***@***.***>,  Author ***@***.***>
> Date: Thu, 01 Jul 2021 01:52:43 -0700
> Subject: Re: [DHI-Roma/gregorovius-frontend] add Hello for Greg (#26)

> Closed #26.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/DHI-Roma/gregorovius-frontend/pull/26#event-49645320
> 48